### ISSUE TITLE
Error with the ROC curve

### ISSUE THREAD

**Issue by diegozea** [tbreloff/MLPlots.jl#8]
@tbreloff I'm using an updated version of _matplotlib_ and the _dev_ branch of _Plots_.

![image](https://cloud.githubusercontent.com/assets/2822757/14866448/10047874-0cc4-11e6-9a52-a2fbe6628496.png)

**Comment by tbreloff** [comment]
I haven't ignored this... I'm in the middle of making a pass through MLPlots to get everything working... but I got sidetracked because I also needed some fixes in OnlineAI, which was part of the MLPlots tests.  I expect to make a big push with MLPlots today, and probably try to register the package in METADATA.

**Comment by tbreloff** [comment]
Question... should this be using the repo https://github.com/davidavdav/ROCAnalysis.jl or https://github.com/diegozea/ROC.jl?

Do you have a good (simple) example to be used for both MLPlots testing and an example on the readme?

**Comment by diegozea** [comment]
Hi @tbreloff ! This should use _ROCAnalysis_ instead of my unregistered _ROC_. However the [ROCR example](https://github.com/diegozea/ROC.jl/blob/master/test/ROCRdata.csv) in my package is good for testing this ;)

**Comment by diegozea** [comment]
@tbreloff The shadow under the ROC curve should be from `x` instead of from `y=x`.

**Comment by diegozea** [comment]
`x` means `y=0`

**Comment by tbreloff** [comment]
So just to be clear, you want `fillrange=0`?  Check: https://github.com/JuliaML/MLPlots.jl#rocanalysis

**Comment by diegozea** [comment]
Exactly, It's fine now in the example :)
